# Generated by Django 5.0.7 on 2024-07-22 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('half_calories_8_in', models.IntegerField(default=0)),
                ('half_calories_12_in', models.IntegerField(default=0)),
                ('half_calories_16_in', models.IntegerField(default=0)),
                ('half_price_8_in', models.FloatField(default=0)),
                ('half_price_12_in', models.FloatField(default=0)),
                ('half_price_16_in', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza_app.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('calories', models.FloatField(default=0)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizza_app.location')),
                ('topping', models.ManyToManyField(to='pizza_app.topping')),
            ],
        ),
    ]
