# Generated by Django 5.0.7 on 2024-07-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('8 inch', '8 inch'), ('12 inch', '12 inch'), ('16 inch', '16 inch')], default='8 inch', max_length=10),
        ),
    ]
