# Generated by Django 5.0.7 on 2024-07-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0002_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.CreateModel(
            name='PizzaLeftTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.topping')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='left_topping',
            field=models.ManyToManyField(related_name='left_toppings', through='pizza_app.PizzaLeftTopping', to='pizza_app.topping'),
        ),
        migrations.CreateModel(
            name='PizzaRightTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.pizza')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.topping')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='right_topping',
            field=models.ManyToManyField(related_name='right_toppings', through='pizza_app.PizzaRightTopping', to='pizza_app.topping'),
        ),
    ]
