# Generated by Django 5.0.7 on 2024-07-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0003_remove_pizza_topping_pizzalefttopping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzarighttopping',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='right_topping',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='left_topping',
        ),
        migrations.RemoveField(
            model_name='pizzalefttopping',
            name='topping',
        ),
        migrations.AddField(
            model_name='pizzalefttopping',
            name='amount_ounces',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pizzalefttopping',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.ingredient'),
        ),
        migrations.AddField(
            model_name='pizzarighttopping',
            name='amount_ounces',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pizzarighttopping',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza_app.ingredient'),
        ),
        migrations.AlterField(
            model_name='pizzalefttopping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_toppings', to='pizza_app.pizza'),
        ),
        migrations.AlterField(
            model_name='pizzarighttopping',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_toppings', to='pizza_app.pizza'),
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
