# Generated by Django 5.0.7 on 2024-07-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0004_remove_pizzarighttopping_topping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzarighttopping',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='pizzarighttopping',
            name='pizza',
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('leftTopping', models.IntegerField(default=0)),
                ('rightTopping', models.IntegerField(default=0)),
                ('half_calories_8_in', models.IntegerField(default=0)),
                ('half_calories_12_in', models.IntegerField(default=0)),
                ('half_calories_16_in', models.IntegerField(default=0)),
                ('half_price_8_in', models.FloatField(default=0)),
                ('half_price_12_in', models.FloatField(default=0)),
                ('half_price_16_in', models.FloatField(default=0)),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza_app.ingredient')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toppings', to='pizza_app.pizza')),
            ],
        ),
        migrations.DeleteModel(
            name='PizzaLeftTopping',
        ),
        migrations.DeleteModel(
            name='PizzaRightTopping',
        ),
    ]
